plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "org.albert.x06_hydrate_me"
    compileSdk = 35

    defaultConfig {
        applicationId = "org.albert.x06_hydrate_me"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    // Old way (groovy?)
//    flavorDimensions "monetization"
//    productFlavors {
//        free {
//            dimension "monetization"
//            applicationIdSuffix ".free"
//            versionNameSuffix "-free"
//        }
//        free {
//            dimension "monetization"
//            applicationIdSuffix ".pro"
//            versionNameSuffix "-pro"
//        }
//    }

//    flavorDimensions.add("monetization")
    flavorDimensions += "monetization"
    productFlavors {
        create("free") {
            dimension = "monetization"
            applicationIdSuffix = ".free"
            versionNameSuffix = "-free"
        }
        create("pro") {
            dimension = "monetization"
            applicationIdSuffix = ".pro"
            versionNameSuffix = "-pro"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = "11"
    }

    viewBinding {
        enable = true
    }
    buildFeatures {
        viewBinding = true
    }

    testOptions {
        unitTests.isIncludeAndroidResources = true
    }
}

dependencies {
    implementation(libs.glide)
    implementation(libs.retrofit)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.navigation.fragment.ktx)
    implementation(libs.androidx.navigation.ui.ktx)

    testImplementation("androidx.test:core:1.6.1")
    testImplementation("org.mockito:mockito-core:5.15.2")
    testImplementation("com.google.truth:truth:1.4.4")
    // JUNIT4 IS ALREADY AT THE END OF THE BLOCK

    // For mocking android specific objects
    // DONT FORGET ABOUT unitTests.isIncludeAndroidResources = true
    testImplementation("org.robolectric:robolectric:4.14.1")
    testImplementation("androidx.test.ext:junit-ktx:1.2.1")

    // For Instrumentation tests.
    // These dependencies introduce something called JUnit4 Rules for managing and
    // interacting with activities and services.
    androidTestImplementation("androidx.test:core-ktx:1.6.1")
    androidTestImplementation("androidx.test.ext:junit-ktx:1.2.1")
    androidTestImplementation("androidx.test:runner:1.6.2")
    // EXPRESSO IS ALREADY AT THE END OF THE BLOCK

    // Autogenerated code.
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
}
//    dependencies {
//        // Including a local library module
//        implementation(project(":localLibrary"))
//        // Including local binaries in /libs folder
//        implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar")))) // Including local binaries in /libs folder
//        // Including a remote library from the repositories configured in the build.gradle.kts files
//        implementation("com.github.bumptech.glide:glide:4.12.0")
//    }
